### ISSUE TITLE
Search bar on darkmode does not apply theming correctly

### ISSUE THREAD

**Issue by BauwenDR** [OSTA-group/osta#76]
# Issue
When dark mode is enabled to search bar does not apply theming correctly

![image](https://github.com/OSTA-group/osta/assets/65725037/9d09f0c7-e144-4a7b-aaa5-a419f07f7d72)

## Discussion(s)
- https://github.com/OSTA-group/osta/discussions/44

**Comment by Luciffffer** [comment]
Same issue with the zoom leaflet.
Doesn't adjust to dark mode.

![image](https://github.com/OSTA-group/osta/assets/116001910/ccc0ccbc-d485-4f65-bc80-e7765fddb3b8)

I'll try to look into fixing the styling
